In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
df = pd.read_csv("test_classification_data.csv", )
X = df.drop('Class', axis = 1)
Y = df['Class']

In [25]:
for i in range (0, 10):
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.15)

    SVClassifier = SVC(kernel = 'poly', degree = i)
#     SVClassifier = SVC(kernel = 'linear')
    SVClassifier.fit(X_train, Y_train)

    y_train_pred = SVClassifier.predict(X_train)
    y_test_pred = SVClassifier.predict(X_test)

    print(confusion_matrix(y_train_pred, Y_train))
    print(classification_report(y_train_pred, Y_train))
    print(confusion_matrix(y_test_pred, Y_test))
    print()

[[16  8]
 [ 0  0]]
              precision    recall  f1-score   support

           C       1.00      0.67      0.80        24
           H       0.00      0.00      0.00         0

    accuracy                           0.67        24
   macro avg       0.50      0.33      0.40        24
weighted avg       1.00      0.67      0.80        24

[[4 1]
 [0 0]]

[[16  8]
 [ 0  0]]
              precision    recall  f1-score   support

           C       1.00      0.67      0.80        24
           H       0.00      0.00      0.00         0

    accuracy                           0.67        24
   macro avg       0.50      0.33      0.40        24
weighted avg       1.00      0.67      0.80        24

[[4 1]
 [0 0]]

[[16  4]
 [ 0  4]]
              precision    recall  f1-score   support

           C       1.00      0.80      0.89        20
           H       0.50      1.00      0.67         4

    accuracy                           0.83        24
   macro avg       0.75      0.90      

C:\Users\juntingma\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\juntingma\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
